// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqOOLydNih4VlDsfEd73mq6TqPhkFB7R8',
    appId: '1:924092660082:web:2a7d695638439e062105eb',
    messagingSenderId: '924092660082',
    projectId: 'fir-task-manager-6bed8',
    authDomain: 'fir-task-manager-6bed8.firebaseapp.com',
    storageBucket: 'fir-task-manager-6bed8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiCuHapWzUj8XVzBgfcaMkQxURg6CsYJs',
    appId: '1:924092660082:android:b21171bbe46b25be2105eb',
    messagingSenderId: '924092660082',
    projectId: 'fir-task-manager-6bed8',
    storageBucket: 'fir-task-manager-6bed8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy3zwFM3K1Cfaa2oCb1RNAuwNuf3gIuKY',
    appId: '1:924092660082:ios:fd41eb9b0b7dd0972105eb',
    messagingSenderId: '924092660082',
    projectId: 'fir-task-manager-6bed8',
    storageBucket: 'fir-task-manager-6bed8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy3zwFM3K1Cfaa2oCb1RNAuwNuf3gIuKY',
    appId: '1:924092660082:ios:fd41eb9b0b7dd0972105eb',
    messagingSenderId: '924092660082',
    projectId: 'fir-task-manager-6bed8',
    storageBucket: 'fir-task-manager-6bed8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqOOLydNih4VlDsfEd73mq6TqPhkFB7R8',
    appId: '1:924092660082:web:45e1c0e942c01c6b2105eb',
    messagingSenderId: '924092660082',
    projectId: 'fir-task-manager-6bed8',
    authDomain: 'fir-task-manager-6bed8.firebaseapp.com',
    storageBucket: 'fir-task-manager-6bed8.firebasestorage.app',
  );
}
